name: GitHub Stats Card
on:
  workflow_dispatch:  # 允许手动运行
  schedule:            # 每天自动更新一次
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # 不会卡住
    permissions:
      contents: write

    steps:
      - name: Generate stats
        uses: yoshi389137/github-stats-card@v1.1.1
        with:
          USERNAME: GGB00M3
          THEME: radical
          SHOW_TOTAL: true
          SHOW_ICONS: true

      - name: Upload
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./
